base: 20
#玩家基础点数
add: 1
#玩家每N秒点数
point: 10
#据点每N秒点数
time: 3
#几秒加一次
min: 2
#最少开始人数
deeppoint: 20
#中间据点每N秒点数
zombie: 1000
#僵尸血量
max: 20
#最大人数
block: 93
#Y达到该值,将无法破坏地图
low: 73
#Y达到最低值
range: 10
#僵尸生成范围
occupytime: 5
#占领据点所需时间