skill:
  蟒王举盾:
      cooldown: 30
      duration: 10
  大天使术:
      cooldown: 30
  千钧束缚:
      cooldown: 30
      duration: 10
  极致狂化:
      cooldown: 30
      duration: 10
  向前冲锋:
      cooldown: 15
      duration: 5
hubserver: hub1
#游戏结束后传送到哪个服务器
game: false
#游戏已经配置完成就可以设置为true
base: 20
#玩家基础点数
add: 10
#玩家每N秒点数
point: 20
#据点每N秒点数
time: 10
#几秒加一次
min: 2
#最少开始人数
deeppoint: 50
#中间据点每N秒点数
zombie: 200
#僵尸血量
max: 20
#最大人数
block: 93
#Y达到该值,将无法破坏地图
low: 73
#Y达到最低值
range: 10
#僵尸生成范围
occupytime: 3
#占领据点所需时间
wait: 9
#等待区宝石上限
ing: 9
#装备区宝石上限
level:
 point:
  1: 100
  2: 200
  3: 300
  4: 400
  5: 600
  6: 900
  7: 1200
  8: 1800
  9: 2300
 armour:
  1: 0
  2: 1
  3: 1
  4: 1
  5: 2
  6: 2
  7: 2
  8: 2
  9: 3
 health:
  1: 100
  2: 200
  3: 500
  4: 600
  5: 700
  6: 800
  7: 1000
  8: 1400
  9: 2000
#血量跟护甲